# Generated by Django 4.1.3 on 2022-11-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finalapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bob_q",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finalapp.hellman_encrypt",
            ),
        ),
    ]
