# Generated by Django 4.1.3 on 2022-11-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finalapp", "0006_alter_bob_q_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="saved_keys",
            name="one_bob",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="saved_keys",
            name="q",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="bob_q",
        ),
    ]
